name = "markdown"
description = "Markdown parser"
version = "24.0.0-20230529"
tags = ["markdown", "gfm", "commonmark"]

authors = ["AdaCore"]
maintainers = ["Max Reznik <reznik@adacore.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"

configuration.disabled = true
project-files = ["gnat/markdown.gpr"]

[origin]
commit = "522ac0682d656f7a8c4a1d0116a8ddd732d2dad9"
url = "git+https://github.com/AdaCore/markdown.git"

[[depends-on]]
vss = ">=24.0.0-20230529"
