name = "markdown"
description = "Markdown parser"
version = "25.0.0-20240612"
tags = ["markdown", "gfm", "commonmark"]

authors = ["AdaCore"]
maintainers = ["Max Reznik <reznik@adacore.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"

configuration.disabled = true
project-files = ["gnat/markdown.gpr"]

[origin]
commit = "c30cce60923521c067a5ae15d67f59a20493bfc5"
url = "git+https://github.com/AdaCore/markdown.git"

[[depends-on]]
vss = ">=24.0.0-20240612"
