name = "markdown"
description = "Markdown parser"
version = "23.0.0-20220721"
tags = ["markdown", "gfm", "commonmark"]

authors = ["AdaCore"]
maintainers = ["Max Reznik <reznik@adacore.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"

configuration.disabled = true
project-files = ["gnat/markdown.gpr"]

[origin]
commit = "dfa0adc12e565afaf9531b7086d324e84ceb88d9"
url = "git+https://github.com/AdaCore/markdown.git"

[[depends-on]]
vss = "23.0.0-20220721"
