name = "libadalang"
description = "Ada semantic analysis library"
version = "24.0.0-20230124"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/libadalang"
tags = ["libadalang", "static-analysis"]
project-files = ["build/libadalang.gpr"]

[origin]
url = "git+https://github.com/AdaCore/libadalang"
commit = "d9ef77865ff2e3bc4b669be9d4b10ae7fcc8953b"

[environment]
PATH.prepend = "${CRATE_ROOT}/env/bin"

[[actions]]
type = "post-fetch"
command = ["bash", "-c", "-x", "python3 -mvenv env; export VIRTUAL_ENV=$PWD/env PATH=$PWD/env/bin:$PATH; pip install -r REQUIREMENTS.dev; pip install $LANGKIT_DIR/; python manage.py generate"]

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
langkit_support = "24.0.0-20230124"
