name = "libadalang"
description = "Ada semantic analysis library"
version = "25.0.0-20231020"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/libadalang"
tags = ["libadalang", "static-analysis"]
project-files = ["build/libadalang.gpr"]

[origin]
url = "git+https://github.com/AdaCore/libadalang"
commit = "71cf07ffe33b0b3420a990f0bbc8e02debdafb00"

[environment]
PATH.prepend = "${CRATE_ROOT}/env/bin"

[[actions]]
type = "post-fetch"
command = ["bash", "-c", "-x", "python3 -mvenv env; export VIRTUAL_ENV=$PWD/env PATH=$PWD/env/bin:$PATH; pip install -r REQUIREMENTS.dev; pip install ${LANGKIT_SUPPORT_ALIRE_PREFIX}/; python manage.py generate"]

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
langkit_support = "25.0.0-20231020"
