name = "libadalang"
description = "Ada semantic analysis library"
version = "24.0.0-20221229"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/libadalang"
tags = ["libadalang", "static-analysis"]
project-files = ["build/libadalang.gpr"]

[origin]
url = "git+https://github.com/AdaCore/libadalang"
commit = "0af03916fd96da8b03435d2aebeae1c7b0eb0843"

[environment]
PATH.prepend = "${CRATE_ROOT}/env/bin"

[[actions]]
type = "post-fetch"
command = ["bash", "-c", "-x", "python3 -mvenv env; export VIRTUAL_ENV=$PWD/env PATH=$PWD/env/bin:$PATH; pip install -r REQUIREMENTS.dev; pip install $LANGKIT_DIR/; python manage.py generate"]

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
langkit_support = "24.0.0-20221229"
