name = "libadalang"
description = "Ada semantic analysis library"
version = "23.0.0-20220204"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/libadalang"
tags = ["libadalang", "static-analysis"]
project-files = ["build/libadalang.gpr"]

[origin]
url = "git+https://github.com/AdaCore/libadalang"
commit = "20a1794c73a2d819eb780b9c05eb87d4eb97dd44"

[environment]
PATH.prepend = "${CRATE_ROOT}/env/bin"

[[actions]]
type = "post-fetch"
command = ["bash", "-c", "-x", "ln -s -v $LANGKIT_DIR langkit; python3 -mvenv env; VIRTUAL_ENV=$PWD/env; pip install -r REQUIREMENTS.dev; python manage.py generate"]

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
langkit_support = "23.0.0-20220204"
