name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "24.0.0-20230719"
tags = ["unicode", "json", "text"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr", "gnat/vss_regexp.gpr"]

[configuration]
generate_ada = false
generate_c = false

[build-switches]
"*".ada_version = "Ada2022"

[origin]
commit = "c10eeb36c7ad5c1f681966fa5e0e7a8cde884dac"
url = "git+https://github.com/AdaCore/VSS.git"

[[depends-on]]
gnat = ">=2020|(>=11 & <=2000)"
