name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "23.0.0-20220204"
tags = ["unicode", "json", "text"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr"]

[origin]
commit = "d3d67ecc1930c9fd37e20d0f26c76555176b7449"
url = "git+https://github.com/AdaCore/VSS.git"

[[depends-on]]
gnat = ">=2020|(>=11 & <=2000)"
