description = "An implementation of the Microsoft's Language Server Protocol for Ada"
name = "ada_language_server"
version = "23.0.14"
website = "https://github.com/AdaCore/ada_language_server"
authors = ["AdaCore"]
licenses = "GPL-3.0-only"
maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/lsp_server.gpr"]
tags = ["lsp", "vscode"]

[environment]
ADA_PROJECT_PATH.set= "${CRATE_ROOT}/subprojects/stubs"

[[depends-on]]
gnatcoll         = "24.0.0-20230220"
libadalang       = "24.0.0-20230220"
libgpr2          = "24.0.0-20230220"
vss              = "24.0.0-20230220"
libadalang_tools = "24.0.0-20230220"
gnatdoc          = "24.0.0-20230220"
spawn            =  "1.1.0-20230220"

[origin]
url = "git+https://github.com/AdaCore/ada_language_server"
commit = "f7059785a2af40afba154a9d72570051df2fea83"