description = "An implementation of the Microsoft's Language Server Protocol for Ada"
name = "ada_language_server"
version = "23.0.13"
website = "https://github.com/AdaCore/ada_language_server"
authors = ["AdaCore"]
licenses = "GPL-3.0-only"
maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/lsp_server.gpr"]
tags = ["lsp", "vscode"]

[environment]
ADA_PROJECT_PATH.set= "${CRATE_ROOT}/subprojects/stubs"

[[depends-on]]
gnatcoll         = "24.0.0-20230124"
libadalang       = "24.0.0-20230124"
libgpr2          = "24.0.0-20230124"
vss              = "24.0.0-20230124"
libadalang_tools = "24.0.0-20230124"
gnatdoc          = "24.0.0-20230124"
spawn            =  "1.1.0-20230124"

[origin]
url = "git+https://github.com/AdaCore/ada_language_server"
commit = "0cd96694d4cb4f148d535b50f3bf61b523ef4792"