description = "An implementation of the Microsoft's Language Server Protocol for Ada"
name = "ada_language_server"
version = "24.0.5"
website = "https://github.com/AdaCore/ada_language_server"
authors = ["AdaCore"]
licenses = "GPL-3.0-only"
maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/lsp_server.gpr"]
tags = ["lsp", "vscode"]

[environment]
ADA_PROJECT_PATH.set= "${CRATE_ROOT}/subprojects/stubs"

[[depends-on]]
gnatcoll         = "25.0.0-20240416"
libadalang       = "25.0.0-20240416"
libgpr2          = "25.0.0-20240416"
vss              = "25.0.0-20240416"
libadalang_tools = "25.0.0-20240416"
lal_refactor     = "25.0.0-20240416"
gnatdoc          = "25.0.0-20240416"
spawn            =  "1.1.0-20231129"

[origin]
url = "git+https://github.com/AdaCore/ada_language_server"
commit = "01071eb82730b235731f871f89a67ee889576c89"
