description = "An implementation of the Microsoft's Language Server Protocol for Ada"
name = "ada_language_server"
version = "23.0.3"
website = "https://github.com/AdaCore/ada_language_server"
authors = ["AdaCore"]
licenses = "GPL-3.0-only"
maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/lsp_server.gpr"]
tags = ["lsp", "vscode"]

[environment]
ADA_PROJECT_PATH.set= "${CRATE_ROOT}/subprojects/stubs"

[[depends-on]]
gnatcoll         = "23.0.0-20220204"
libadalang       = "23.0.0-20220204"
libgpr2          = "23.0.0-20220204"
vss              = "23.0.0-20220204"
libadalang_tools = "23.0.0-20220204"
spawn            =  "1.1.0-20211202"

[origin]
url = "git+https://github.com/AdaCore/ada_language_server"
commit = "9e4a2e15fc7da6adc9a1cf2e299bc1d40786ad8c"