name = "prettier_ada"
description = "A library to create formatters for any language."
version = "25.0.0-20240612"

authors = ["AdaCore"]
maintainers = ["João Azevedo <azevedo@adacore.com>"]
maintainers-logins = ["joaopsazevedo"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/prettier-ada"
tags = ["format", "prettier"]

[[depends-on]]
gnatcoll         = "*"
vss              = "*"

[origin]
url = "git+https://github.com/AdaCore/prettier-ada"
commit = "67239e2a7f96285b5e2363cd73b80c1c253ec3b0"
