name = "prettier_ada"
description = "A library to create formatters for any language."
version = "25.0.0-20240130"

authors = ["AdaCore"]
maintainers = ["João Azevedo <azevedo@adacore.com>"]
maintainers-logins = ["joaopsazevedo"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/prettier-ada"
tags = ["format", "prettier"]

[[depends-on]]
gnatcoll         = "25.0.0-20231207"
vss              = "25.0.0-20231207"

[origin]
url = "git+https://github.com/AdaCore/prettier-ada"
commit = "1ebb91c8fe70dbb91a09aba5298d13175f1f68a8"
