name = "lal_refactor"
description = "Source code refactoring tools for the Ada"
version = "24.0.0-20230719"

authors = ["AdaCore"]
maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/lal-refactor"
tags = ["static-analysis"]
project-files = ["gnat/lal_refactor.gpr"]

[origin]
url = "git+https://github.com/AdaCore/lal-refactor"
commit = "441bfaecd67f372714c9b3247c4424423949e30c"

[[actions]]
type = "post-fetch"
command = ["bash", "-c", "-x", "echo hello!"]

[[depends-on]]
libadalang_tools = "*"
