name = "lal_refactor"
description = "Source code refactoring tools for the Ada"
version = "25.0.0-20240219"

authors = ["AdaCore"]
maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/lal-refactor"
tags = ["static-analysis"]
project-files = ["gnat/lal_refactor.gpr"]

[origin]
url = "git+https://github.com/AdaCore/lal-refactor"
commit = "b004afc3ac20a35eccda47a45efa3851b4dc5ee0"

[[depends-on]]
libadalang_tools = "*"
