name = "langkit_support"
description = "Runtime support library for Langkit-generated libraries"
version = "23.0.0-20220721"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/langkit"

project-files = ["langkit/support/langkit_support.gpr"]

[origin]
url = "git+https://github.com/AdaCore/langkit"
commit = "3f9cf09bf54f6522a20fc14c28d0e70d07094c2b"

[environment]
LANGKIT_DIR.set= "${CRATE_ROOT}"

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
