name = "langkit_support"
description = "Runtime support library for Langkit-generated libraries"
version = "25.0.0-20240612"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/langkit"

project-files = ["langkit/support/langkit_support.gpr"]

[origin]
url = "git+https://github.com/AdaCore/langkit"
commit = "98e15caba1061233a079dadf50ca361b92ab4ed0"

[[actions]]
type = "post-fetch"
command = ["bash", "-c", "-x", "rm -rf langkit/adasat && cp -r ${ADASAT_ALIRE_PREFIX} langkit/adasat"]

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
adasat = "*"
