name = "langkit_support"
description = "Runtime support library for Langkit-generated libraries"
version = "25.0.0-20240416"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/langkit"

project-files = ["langkit/support/langkit_support.gpr"]

[origin]
url = "git+https://github.com/AdaCore/langkit"
commit = "ba6f6e5dbc29098731a21d087d059db6cfb5cbed"

[[actions]]
type = "post-fetch"
command = ["bash", "-c", "-x", "rm -rf langkit/adasat && cp -r ${ADASAT_ALIRE_PREFIX} langkit/adasat"]

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
adasat = "*"
