name = "langkit_support"
description = "Runtime support library for Langkit-generated libraries"
version = "23.0.0-20211202"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/langkit"

project-files = ["support/langkit_support.gpr"]

[origin]
url = "git+https://github.com/AdaCore/langkit"
commit = "41045da6b98b06bd670b700ef052d1e6aa4a870d"

[environment]
LANGKIT_DIR.set= "${CRATE_ROOT}"

[[depends-on]]
gnatcoll = "^22"
gnatcoll_iconv = "^22"
gnatcoll_gmp = "^22"
