name = "langkit_support"
description = "Runtime support library for Langkit-generated libraries"
version = "23.0.0-20220817"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/langkit"

project-files = ["langkit/support/langkit_support.gpr"]

[origin]
url = "git+https://github.com/AdaCore/langkit"
commit = "540f2d32425def88d2f0d4310cb98db7f6cec415"

[environment]
LANGKIT_DIR.set= "${CRATE_ROOT}"

[[depends-on]]
gnatcoll = "*"
gnatcoll_bindings = "*"
