name = "gnatcoll"
version = "24.0.0-20230126"
description = "GNAT Components Collection - Core packages"
website = "https://github.com/adacore/gnatcoll-core"
authors = ["AdaCore"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["gnatcoll.gpr"]
tags = ["gnatcoll", "json", "email", "refcount", "projects", "gpr", "vfs"]

[configuration]
disabled = true

[gpr-externals]
GNATCOLL_ATOMICS = ["intrinsic", "mutex"]
GNATCOLL_BUILD_MODE = ["DEBUG", "PROD"]
GNATCOLL_OS = ["windows", "unix", "osx"]
LIBRARY_TYPE = ["static", "relocatable", "static-pic"]

[gpr-set-externals."case(os)".linux]
GNATCOLL_OS = "unix"
[gpr-set-externals."case(os)".macos]
GNATCOLL_OS = "osx"
[gpr-set-externals."case(os)".windows]
GNATCOLL_OS = "windows"

[gpr-set-externals]
GNATCOLL_VERSION = "24.0.0"

[[depends-on]]
libgpr = "24.0.0-20230126"

[origin]
url = "git+https://github.com/AdaCore/gnatcoll-core.git"
commit = "9cf086bc12e2f6a865428f055266e5aa8781ddbc"
