name = "libadalang_tools"
description = "Ada semantic analysis library extension and tools"
version = "23.0.0-20220204"

authors = ["AdaCore"]
maintainers = ["Pierre-Marie de Rodat <pmderodat@kawie.fr>"]
maintainers-logins = ["pmderodat"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/libadalang-tools"
tags = ["libadalang", "static-analysis"]
project-files = ["src/lal_tools.gpr", "src/build.gpr"]
executables = ["gnatmetric", "gnatpp", "gnatstub", "gnattest"]

[origin]
url = "git+https://github.com/AdaCore/libadalang-tools"
commit = "624c1af82a9374dc8a87d5dd2b75742551d79ef1"

[[depends-on]]
libadalang = "23.0.0-20220204"
